#HA esphome rs485Max esp32 PH EC TEMP NPK HUM Soil sensor 12v

esphome:
  name: bodensensor3
  friendly_name: bodensensor3

esp32:
  board: esp32dev
  framework:
    type: arduino



# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bodensensor3 Fallback Hotspot"
    password: ""


uart:
  id: uart_modbus
  tx_pin: GPIO19
  rx_pin: GPIO18
  stop_bits: 1
  baud_rate: 9600

modbus:
  flow_control_pin: GPIO4
  id: modbus1
  send_wait_time: 300ms  

modbus_controller:
- id: modbus_device
  address: 0x01
  modbus_id: modbus1
  setup_priority: -10

logger:
  level: DEBUG

sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Soil Temperature"
    register_type: holding 
    address: 0x0013
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Soil Moisture"
    register_type: holding
    address: 0x0012
    unit_of_measurement: "%"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Soil pH"
    register_type: holding
    address: 0x0006
    unit_of_measurement: "-"
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Soil Conductivity"
    register_type: holding
    address: 0x0015
    unit_of_measurement: "µS/cm"
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Soil Nitrogen"
    register_type: holding
    address: 0x001E
    unit_of_measurement: "mg/kg"
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Soil Phosphorus"
    register_type: holding
    address: 0x001F
    unit_of_measurement: "mg/kg"
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Soil Potassium"
    register_type: holding
    address: 0x0020
    unit_of_measurement: "mg/kg"
    value_type: U_WORD
    accuracy_decimals: 0
